package Cryptol.PRESENT

import spinal.core._
import spinal.lib._

class permutation extends Component {
	val io = new Bundle {
		val stateIn		= in  Bits(64 bits)
		val stateOut 	= out Bits(64 bits)
	}
	
	io.stateOut( 0) := io.stateIn( 0)
	io.stateOut(16) := io.stateIn( 1)
	io.stateOut(32) := io.stateIn( 2)
	io.stateOut(48) := io.stateIn( 3)
	io.stateOut( 1) := io.stateIn( 4)
	io.stateOut(17) := io.stateIn( 5)
	io.stateOut(33) := io.stateIn( 6)
	io.stateOut(49) := io.stateIn( 7)
	io.stateOut( 2) := io.stateIn( 8)
	io.stateOut(18) := io.stateIn( 9)
	io.stateOut(34) := io.stateIn(10)
	io.stateOut(50) := io.stateIn(11)
	io.stateOut( 3) := io.stateIn(12)
	io.stateOut(19) := io.stateIn(13)
	io.stateOut(35) := io.stateIn(14)
	io.stateOut(51) := io.stateIn(15)
	
	io.stateOut( 4) := io.stateIn(16)
	io.stateOut(20) := io.stateIn(17)
	io.stateOut(36) := io.stateIn(18)
	io.stateOut(52) := io.stateIn(19)
	io.stateOut( 5) := io.stateIn(20)
	io.stateOut(21) := io.stateIn(21)
	io.stateOut(37) := io.stateIn(22)
	io.stateOut(53) := io.stateIn(23)
	io.stateOut( 6) := io.stateIn(24)
	io.stateOut(22) := io.stateIn(25)
	io.stateOut(38) := io.stateIn(26)
	io.stateOut(54) := io.stateIn(27)
	io.stateOut( 7) := io.stateIn(28)
	io.stateOut(23) := io.stateIn(29)
	io.stateOut(39) := io.stateIn(30)
	io.stateOut(55) := io.stateIn(31)
	
	io.stateOut( 8) := io.stateIn(32)
	io.stateOut(24) := io.stateIn(33)
	io.stateOut(40) := io.stateIn(34)
	io.stateOut(56) := io.stateIn(35)
	io.stateOut( 9) := io.stateIn(36)
	io.stateOut(25) := io.stateIn(37)
	io.stateOut(41) := io.stateIn(38)
	io.stateOut(57) := io.stateIn(39)
	io.stateOut(10) := io.stateIn(40)
	io.stateOut(26) := io.stateIn(41)
	io.stateOut(42) := io.stateIn(42)
	io.stateOut(58) := io.stateIn(43)
	io.stateOut(11) := io.stateIn(44)
	io.stateOut(27) := io.stateIn(45)
	io.stateOut(43) := io.stateIn(46)
	io.stateOut(59) := io.stateIn(47)
	
	io.stateOut(12) := io.stateIn(48)
	io.stateOut(28) := io.stateIn(49)
	io.stateOut(44) := io.stateIn(50)
	io.stateOut(60) := io.stateIn(51)
	io.stateOut(13) := io.stateIn(52)
	io.stateOut(29) := io.stateIn(53)
	io.stateOut(45) := io.stateIn(54)
	io.stateOut(61) := io.stateIn(55)
	io.stateOut(14) := io.stateIn(56)
	io.stateOut(30) := io.stateIn(57)
	io.stateOut(46) := io.stateIn(58)
	io.stateOut(62) := io.stateIn(59)
	io.stateOut(15) := io.stateIn(60)
	io.stateOut(31) := io.stateIn(61)
	io.stateOut(47) := io.stateIn(62)
	io.stateOut(63) := io.stateIn(63)
	
}
